// Unit 1 practice items -- Segment A (Topics 1.1-1.4).
// All items are original; none are reused from official AP Classroom
// Progress Check assessments, which remain reserved for actual quizzes.
export const UNIT1_ITEMS = [

  // ---- 1.1 ----
  { id: "1.1-b1", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.A", prompt: "Which of the following best describes sequencing in an algorithm?",
    choices: ["Repeating a step until a condition is met", "Completing the steps of a process in a specific order, one at a time", "Choosing between two different steps based on a condition", "Skipping steps that are not needed"],
    answer: 1, explanation: "Sequencing means completing the steps of a process in a specific order, one at a time." },
  { id: "1.1-b2", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.B", prompt: "What is the primary role of a compiler?",
    choices: ["To execute a program and display its output", "To translate code into a diagram representing its logic", "To check code for certain types of errors before the program runs", "To fix logic errors automatically before a program runs"],
    answer: 2, explanation: "A compiler checks code for certain types of errors (syntax errors) before the program is allowed to run." },
  { id: "1.1-b3", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.C", prompt: "A student writes a program, but it fails to compile because a semicolon is missing at the end of a statement. What type of error is this?",
    choices: ["Syntax error", "Logic error", "Run-time error", "Exception"],
    answer: 0, explanation: "A missing semicolon breaks the rules of the language's syntax, so the compiler catches it as a syntax error." },
  { id: "1.1-b4", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.A", prompt: "A recipe for baking a cake is written in plain English, listing each step in order (mix dry ingredients, add wet ingredients, pour into pan, bake). Which of the following best describes this recipe?",
    choices: ["It cannot be an algorithm because it is not written in a programming language like Java.", "It is an algorithm, because it defines a step-by-step process to accomplish a task, and algorithms do not need to be written in a specific programming language.", "It is an algorithm only once someone translates it into Java code.", "It is a compiler, because it converts instructions into a result."],
    answer: 1, explanation: "Algorithms are step-by-step processes and can be represented in written language or diagrams -- they don't need to be written in a programming language." },
  { id: "1.1-b5", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.B", prompt: "A student writes a Java program but forgets to include a closing curly brace } at the end of a class. What will happen when the student tries to run the program?",
    choices: ["The program will run normally, ignoring the missing brace.", "The program will run but produce an incorrect result.", "The compiler will detect an error, and the student must fix it before the program can run.", "The program will run and then crash partway through with an exception."],
    answer: 2, explanation: "A missing brace is a syntax error, which the compiler detects. It must be fixed before the program can be run." },
  { id: "1.1-b6", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.C", prompt: "A program is supposed to print the larger of two numbers, but due to a mistake in the code's conditional logic, it sometimes prints the smaller number instead. The program compiles and runs without crashing. What type of error is this?",
    choices: ["Syntax error", "Logic error", "Run-time error", "Exception"],
    answer: 1, explanation: "The program runs without crashing but produces an incorrect result -- that's a logic error, found by testing." },
  { id: "1.1-b7", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.C", prompt: "A program compiles with no errors. While running, it attempts to access the 10th element of a list that only has 5 elements, and the program crashes immediately with an error message. What type of error is this?",
    choices: ["Syntax error", "Logic error", "Run-time error (exception)", "Compiler error"],
    answer: 2, explanation: "This is a run-time error (specifically an exception) -- it occurs during execution and was not caught by the compiler." },
  { id: "1.1-i1", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "A student wants to write an algorithm to determine how many identical square tiles, each covering exactly one square foot, are needed to completely cover a rectangular floor. Which of the following algorithms correctly determines this?",
    choices: ["Step 1: Add the floor's length and width. Step 2: Multiply the result by 2.", "Step 1: Multiply the floor's length by its width.", "Step 1: Add the floor's length and width.", "Step 1: Subtract the floor's width from its length. Step 2: Multiply the result by 2."],
    answer: 1, explanation: "The number of unit tiles needed equals the floor's area, which is found by multiplying its length by its width." },
  { id: "1.1-i2", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "A painter wants an algorithm to determine the total amount of paint, in gallons, needed to cover two rectangular walls. Each wall requires paint equal to its height multiplied by its width, and one gallon covers exactly one square foot. Which of the following algorithms correctly determines the total gallons needed?",
    choices: ["Step 1: Multiply wall1's height by wall2's height. Step 2: Multiply wall1's width by wall2's width. Step 3: Add the results.", "Step 1: Multiply wall1's height by wall1's width. Step 2: Multiply wall2's height by wall2's width. Step 3: Add the results.", "Step 1: Add wall1's height and width. Step 2: Add wall2's height and width. Step 3: Multiply the results.", "Step 1: Add wall1's height to wall2's height. Step 2: Add wall1's width to wall2's width. Step 3: Multiply the results."],
    answer: 1, explanation: "Each wall's paint need is its own height x width. Adding the two individual amounts gives the total gallons needed." },
  { id: "1.1-i3", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.C", prompt: "A student wrote a program that is supposed to determine whether a number entered by the user is even or odd. The program compiles and runs without crashing, but it sometimes labels even numbers as odd. Which of the following strategies is most likely to help the student identify the source of the error?",
    choices: ["Rewriting the entire program from scratch without examining the current code", "Inserting print statements to display the value of key variables at different points in the program", "Assuming the compiler will flag the mistake the next time the program is compiled", "Running the program again without making any changes, hoping the error does not reoccur"],
    answer: 1, explanation: "Print statements reveal what the program is doing as it runs, which helps pinpoint exactly where the incorrect result is introduced." },
  { id: "1.1-c1", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.A", prompt: "A student is designing an algorithm to determine the largest of three numbers, a, b, and c. Which sequence of steps correctly accomplishes this task for all possible values of a, b, and c?",
    choices: ["Step 1: Compare a and b, keep the larger. Step 2: Compare the result to c, keep the larger.", "Step 1: Compare a and b, keep the larger. Step 2: Compare a and c, keep the larger.", "Step 1: Add a, b, and c. Step 2: Divide by 3.", "Step 1: Compare b and c, keep the smaller. Step 2: Compare the result to a, keep the smaller."],
    answer: 0, explanation: "Only option A correctly carries the running largest value into the second comparison for every case." },
  { id: "1.1-c2", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.B", prompt: "A student's program compiles with no errors, but every time it runs, it closes unexpectedly partway through and displays a message referring to a \"NullPointerException.\" Which of the following best explains this situation?",
    choices: ["The compiler failed to catch a syntax error, causing this behavior.", "This is a logic error, since the program produced an unexpected outcome.", "This is a run-time error called an exception, which occurs during execution and was not caught by the compiler.", "This is not a real error; the program is working as intended."],
    answer: 2, explanation: "An exception is a run-time error that occurs during execution and interrupts the program -- it isn't something the compiler could have caught." },
  { id: "1.1-c3", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.C", prompt: "A program compiles and runs to completion without crashing, but it consistently calculates an incorrect average for a list of test scores. Which type of error is most likely present, and how would it most likely be found?",
    choices: ["Syntax error; found by the compiler before the program runs.", "Logic error; found by testing the program with known input and checking the output.", "Run-time error; found because the program terminates abnormally.", "Exception; found because the program displays an error message during execution."],
    answer: 1, explanation: "The program runs to completion but gives a wrong result -- a logic error, which is found by testing with known inputs." },
  { id: "1.1-c4", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.A", prompt: "A programmer wants to find the average of a list of numbers. She first writes out the steps in plain English: \"Add all the numbers together. Divide the sum by how many numbers there are.\" She later translates these steps into Java code. Which of the following is true about the relationship between her plain-English steps and her Java code?",
    choices: ["The plain-English steps are not a real algorithm until they are written in Java.", "Both the plain-English steps and the Java code represent the same algorithm; Java is just one way to implement it.", "The Java code is the algorithm, and the plain-English steps are just documentation.", "An algorithm can only exist once it has been compiled."],
    answer: 1, explanation: "The plain-English steps already form the algorithm. Java is simply one language used to implement that same algorithm." },
  { id: "1.1-c5", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.B", prompt: "A student writes two separate code segments. Segment 1 is missing a semicolon at the end of a statement. Segment 2 has all correct syntax, but divides a number by a variable that turns out to be 0 when the program runs. Which of the following correctly describes what will happen with each segment?",
    choices: ["Both segments will fail to compile.", "Segment 1 will fail to compile; Segment 2 will compile but may cause a run-time error when executed.", "Segment 1 will compile and run correctly; Segment 2 will fail to compile.", "Both segments will compile and run without any errors."],
    answer: 1, explanation: "Segment 1 has a syntax error, caught at compile time. Segment 2 is syntactically valid but can trigger a run-time error (division by zero) only once it executes." },
  { id: "1.1-c6", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.C", prompt: "Situation 1: The program will not compile because a variable name is misspelled in one place. Situation 2: The program compiles and runs to completion, but consistently gives the wrong answer for a calculation. Situation 3: The program compiles, runs, and unexpectedly stops partway through with a \"division by zero\" message. Which of the following correctly identifies the error type for each situation?",
    choices: ["1: Logic error, 2: Syntax error, 3: Run-time error", "1: Syntax error, 2: Logic error, 3: Run-time error (exception)", "1: Run-time error, 2: Syntax error, 3: Logic error", "1: Syntax error, 2: Run-time error, 3: Logic error"],
    answer: 1, explanation: "1 is a syntax error (caught by the compiler). 2 is a logic error (wrong result, found by testing). 3 is a run-time error / exception (crashes during execution)." },

  // ---- 1.2 ----
  { id: "1.2-b1", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.A", prompt: "Which of the following best distinguishes a primitive data type from a reference data type in Java?",
    choices: ["Primitive types can only store whole numbers, while reference types can store decimals.", "Primitive types directly store a value of that type, while reference types are used to define objects that are not primitive types.", "Primitive types are used only for text, while reference types are used only for numbers.", "There is no meaningful difference between primitive and reference types."],
    answer: 1, explanation: "A primitive type directly stores a value of that type. A reference type is used to define objects that are not primitive types." },
  { id: "1.2-b2", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.A", prompt: "A programmer needs a variable to store a person's exact age in whole years. Which category of data type is most appropriate?",
    choices: ["Reference type, because age is a property of a person object", "Primitive type, because the value is a number", "Neither, since age does not need to be stored", "Reference type, because ages can be compared using =="],
    answer: 1, explanation: "A whole number like age is best represented with a primitive numeric type." },
  { id: "1.2-b3", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "Which of the following correctly declares and initializes an int variable named count with the value 10?",
    choices: ["int count = 10;", "double count = 10;", "int count = \"10\";", "count int = 10;"],
    answer: 0, explanation: "int count = 10; correctly declares an int variable and initializes it with the integer value 10." },
  { id: "1.2-b4", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "A variable needs to store a temperature reading that may include decimal values, such as 98.6. Which data type is most appropriate for this variable?",
    choices: ["int", "boolean", "double", "String"],
    answer: 2, explanation: "double is the primitive type used for real numbers, including decimal values." },
  { id: "1.2-b5", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "Which of the following values could correctly be stored in a variable declared as boolean isReady;?",
    choices: ["1", "\"true\"", "true", "0"],
    answer: 2, explanation: "A boolean variable can only store the values true or false, not the numbers 1/0 or the String \"true\"." },
  { id: "1.2-b6", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "Which of the following best describes a variable in Java?",
    choices: ["A fixed value that cannot be changed once the program starts running", "A storage location that holds a value, which can change while the program runs, and has a name and an associated data type", "A type of method used to perform calculations", "A keyword used only to declare classes"],
    answer: 1, explanation: "A variable is a storage location with a name and data type, whose value can change while the program runs." },
  { id: "1.2-i1", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A program needs variables to represent whether a package has been delivered and the number of days it has been in transit. Which of the following pairs of variable declarations is most appropriate?",
    choices: ["boolean delivered; boolean daysInTransit;", "int delivered; int daysInTransit;", "boolean delivered; int daysInTransit;", "int delivered; boolean daysInTransit;"],
    answer: 2, explanation: "Whether something is true/false fits boolean; a count of days fits int." },
  { id: "1.2-i2", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.B", prompt: "A student declares a variable using the statement: double price = 20; Which of the following is true about this statement?",
    choices: ["It causes a compile-time error because 20 is not a decimal literal.", "It is valid; the int value 20 is automatically converted to the double value 20.0 when stored in price.", "It is valid, but price will store the value 20 as an int.", "It is valid only if 20 is written as 20.0."],
    answer: 1, explanation: "An int literal can be assigned to a double variable; it is automatically converted (widened) to 20.0." },
  { id: "1.2-i3", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A class named Robot is used to create Robot objects. Which of the following statements about a variable declared as Robot myRobot; is true?",
    choices: ["myRobot is a primitive type variable that stores a Robot value directly.", "myRobot is a reference type variable, since Robot is not one of the primitive types used in this course.", "myRobot can only store the values true or false.", "myRobot must be declared using the keyword int."],
    answer: 1, explanation: "Robot is not one of the three primitive types (int, double, boolean), so myRobot is a reference type variable." },
  { id: "1.2-c1", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.A", prompt: "Consider the following variable declarations: int score; boolean isPassing; String name; double average; Which of these variables is a reference type?",
    choices: ["score", "isPassing", "name", "average"],
    answer: 2, explanation: "String is not one of the three primitive types in this course, so name is a reference type. The others are primitive types." },
  { id: "1.2-c2", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.B", prompt: "A program needs to track a student's exact exam score (which may include decimal points, such as 87.5) and whether the student passed the exam. Which pair of declarations is most appropriate?",
    choices: ["int examScore; boolean passed;", "double examScore; boolean passed;", "double examScore; int passed;", "boolean examScore; double passed;"],
    answer: 1, explanation: "A decimal score needs double; a true/false result needs boolean." },
  { id: "1.2-c3", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.B", prompt: "A student attempts to declare a variable as follows: float temperature = 98.6f; Which of the following best explains why this is problematic in the context of this course?",
    choices: ["float is not a valid keyword in Java.", "The value 98.6f is not a valid literal.", "float is not one of the three primitive data types (int, double, boolean) covered in this course; double should be used instead.", "Variables cannot store decimal values in Java."],
    answer: 2, explanation: "Only int, double, and boolean are the primitive types used in this course; float is outside its scope." },
  { id: "1.2-c4", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.A", prompt: "A parking garage program needs to track: the number of open parking spots (a whole number), and whether the garage is currently full. Which of the following declarations is most appropriate?",
    choices: ["double openSpots; boolean isFull;", "int openSpots; boolean isFull;", "boolean openSpots; int isFull;", "int openSpots; double isFull;"],
    answer: 1, explanation: "A whole-number count fits int; a true/false condition fits boolean." },
  { id: "1.2-c5", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.B", prompt: "Which of the following code segments will NOT compile?",
    choices: ["int x = 5;", "double y = 5;", "boolean b = 1;", "double z = 5.0;"],
    answer: 2, explanation: "A boolean variable cannot be assigned an int value like 1 -- it must be assigned true or false." },

  // ---- 1.3 ----
  { id: "1.3-b1", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.A", prompt: "What is the difference between System.out.print and System.out.println?",
    choices: ["print displays text in red; println displays text in black.", "println moves the cursor to a new line after displaying its output; print does not.", "print can only display numbers; println can only display text.", "There is no difference; they behave identically."],
    answer: 1, explanation: "println moves the cursor to a new line after displaying its output, while print does not." },
  { id: "1.3-b2", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.A", prompt: "What is printed as a result of executing the following code segment?\nSystem.out.print(\"A\");\nSystem.out.println(\"B\");\nSystem.out.print(\"C\");",
    choices: ["ABC", "A\nBC", "AB\nC", "A B C (each on its own line)"],
    answer: 2, explanation: "print(\"A\") and println(\"B\") produce \"AB\" followed by a new line, then print(\"C\") continues on the next line." },
  { id: "1.3-b3", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.B", prompt: "Which of the following is a string literal?",
    choices: ["count", "25", "\"Hello\"", "true"],
    answer: 2, explanation: "A string literal is a sequence of characters enclosed in double quotes, such as \"Hello\"." },
  { id: "1.3-b4", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.B", prompt: "Which of the following escape sequences causes a new line to be printed within a string?",
    choices: ["\\t", "\\n", "\\\\", "\\\""],
    answer: 1, explanation: "The escape sequence \\n represents a newline." },
  { id: "1.3-b5", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.C", prompt: "What is the result of the expression 7 / 2 in Java, where both values are int literals?",
    choices: ["3.5", "3", "4", "3.0"],
    answer: 1, explanation: "Dividing two int values gives only the integer portion of the quotient, so 7 / 2 evaluates to 3." },
  { id: "1.3-b6", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.C", prompt: "What is the result of the expression 7.0 / 2 in Java?",
    choices: ["3", "3.5", "4", "3.0"],
    answer: 1, explanation: "When at least one value is a double, the division evaluates to the full quotient: 3.5." },
  { id: "1.3-b7", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.C", prompt: "What is the value of the expression 10 % 3?",
    choices: ["3", "1", "0", "3.33"],
    answer: 1, explanation: "The remainder operator gives the remainder after division: 10 divided by 3 leaves a remainder of 1." },
  { id: "1.3-i1", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of x after the following code segment executes?\nint x = 2 + 3 * 4;",
    choices: ["20", "14", "24", "9"],
    answer: 1, explanation: "Multiplication has precedence over addition: 3 * 4 = 12, then 2 + 12 = 14." },
  { id: "1.3-i2", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of result after the following code executes?\ndouble result = 5 + 3 / 2;",
    choices: ["6.5", "6.0", "4.0", "6"],
    answer: 1, explanation: "3 / 2 is int division, giving 1. Then 5 + 1 = 6, widened to the double value 6.0 when stored in result." },
  { id: "1.3-i3", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.B", prompt: "What is printed as a result of executing the following statement?\nSystem.out.println(\"She said \\\"hello\\\".\");",
    choices: ["She said hello.", "She said \"hello\".", "She said \\\"hello\\\".", "An error occurs because quotes cannot be used inside a string."],
    answer: 1, explanation: "The escape sequence \\\" prints an actual double-quote character." },
  { id: "1.3-c1", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "What happens when the following code segment executes?\nint a = 10;\nint b = 0;\nint result = a / b;\nSystem.out.print(result);",
    choices: ["The code prints 0.", "The code prints Infinity.", "The code throws an ArithmeticException at run time.", "The code fails to compile."],
    answer: 2, explanation: "Dividing an int by the int value 0 throws an ArithmeticException at run time." },
  { id: "1.3-c2", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "What is the value of x after the following code executes?\nint x = (2 + 3) * 4 % 5;",
    choices: ["0", "20", "4", "1"],
    answer: 0, explanation: "(2 + 3) = 5, then 5 * 4 = 20, then 20 % 5 = 0." },
  { id: "1.3-c3", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "Consider the expression: 9 / 2 * 1.0. Which best describes how this expression is evaluated, and what is its final value?",
    choices: ["The entire expression is treated as a double from the start, giving 4.5.", "9 / 2 is evaluated first as int division, giving 4; then 4 * 1.0 gives 4.0.", "2 * 1.0 is evaluated first, giving 2.0; then 9 / 2.0 gives 4.5.", "The expression does not compile because int and double values cannot be mixed."],
    answer: 1, explanation: "Operators of equal precedence evaluate left to right: 9 / 2 (int division) = 4 first, then 4 * 1.0 = 4.0." },
  { id: "1.3-c4", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.A", prompt: "What is printed as a result of executing the following code segment?\nSystem.out.print(\"Score: \");\nSystem.out.println(100);\nSystem.out.print(\"Done\");",
    choices: ["Score: 100 Done", "Score: 100\nDone", "Score: \n100Done", "Score:100Done"],
    answer: 1, explanation: "print keeps the cursor on the same line, then println moves to a new line before Done is printed." },
  { id: "1.3-c5", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "What is the value of y after the following code executes?\nint y = 17 % 5 + 17 / 5;",
    choices: ["5", "3.4", "2", "8.4"],
    answer: 0, explanation: "17 % 5 = 2, and 17 / 5 = 3 (int division). 2 + 3 = 5." },
  { id: "1.3-c6", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "Which of the following expressions will cause an ArithmeticException when evaluated?",
    choices: ["5 / 2", "5 / 0", "5.0 / 0", "5 % 2"],
    answer: 1, explanation: "Dividing an int by the int value 0 throws an ArithmeticException. Dividing a double by 0 does not." },

  // ---- 1.4 ----
  { id: "1.4-b1", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "What does the assignment operator = do in a statement like x = 5;?",
    choices: ["It checks whether x is equal to 5.", "It stores the value of the expression on the right side into the variable on the left side.", "It declares a new variable named x.", "It compares x to 5 and returns true or false."],
    answer: 1, explanation: "The assignment operator stores the value of the right-hand expression into the variable on the left." },
  { id: "1.4-b2", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "Which of the following best describes when a variable must be assigned a value in Java?",
    choices: ["A variable never needs to be assigned a value.", "A variable must be assigned a value before it can be used in an expression.", "A variable is automatically assigned a value of 0 and never needs explicit assignment.", "A variable only needs a value if it is a boolean."],
    answer: 1, explanation: "Every variable must be assigned a value before it can be used in an expression." },
  { id: "1.4-b3", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "Which of the following is true about the value null in Java?",
    choices: ["null can be assigned to any primitive type, such as int or double.", "null can be assigned to a reference type to indicate it is not associated with any object.", "null is a keyword used only inside loops.", "null automatically converts to the value 0."],
    answer: 1, explanation: "null is a special value used to indicate that a reference type variable is not associated with any object." },
  { id: "1.4-b4", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "During program execution, what does an expression like 3 + 4 evaluate to?",
    choices: ["Nothing; expressions are only used for output.", "A single value, which has a type based on how the expression was evaluated.", "A method call.", "A variable declaration."],
    answer: 1, explanation: "An expression is evaluated to produce a single value, and that value has a type based on the evaluation." },
  { id: "1.4-b5", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.B", prompt: "Which class is commonly used in this course to obtain text input from the keyboard?",
    choices: ["System", "Scanner", "String", "Math"],
    answer: 1, explanation: "The Scanner class is one way to obtain text input from the keyboard." },
  { id: "1.4-b6", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "What is the value of y after the following code executes?\nint x = 4;\nint y = x;\nx = 10;",
    choices: ["4", "10", "0", "14"],
    answer: 0, explanation: "y is assigned the value of x (4) at that moment. Changing x afterward does not affect y." },
  { id: "1.4-i1", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "What is printed as a result of executing the following code segment?\nint a = 5;\na = a + 3;\na = a * 2;\nSystem.out.print(a);",
    choices: ["8", "16", "13", "5"],
    answer: 1, explanation: "a becomes 5 + 3 = 8, then 8 * 2 = 16." },
  { id: "1.4-i2", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "Consider the following code segment:\nString name = null;\nSystem.out.print(name);\nWhich of the following best describes what happens?",
    choices: ["The code fails to compile because null cannot be assigned to a String.", "The code compiles and runs, printing the word null.", "The code throws an exception at compile time.", "The code compiles but prints nothing at all."],
    answer: 1, explanation: "String is a reference type, so it can be assigned null. Printing a null reference displays the word null." },
  { id: "1.4-i3", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "Consider the following code segment:\nint p = 3;\nint q = 8;\nint temp = p;\np = q;\nq = temp;\nSystem.out.println(p);\nSystem.out.println(q);\nWhat is printed?",
    choices: ["3 then 8", "8 then 3", "3 then 3", "8 then 8"],
    answer: 1, explanation: "This swaps the values: p becomes 8 (q's original value) and q becomes 3 (saved in temp)." },
  { id: "1.4-c1", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "Consider the following code segment:\nint total;\nSystem.out.print(total);\nWhich of the following best describes the result of executing this code?",
    choices: ["It prints 0, since int variables default to 0.", "It fails to compile, since total is used before it has been assigned a value.", "It prints null.", "It throws a run-time exception, but the program continues."],
    answer: 1, explanation: "A local variable must be assigned a value before it can be used in an expression; using it first causes a compile-time error." },
  { id: "1.4-c2", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "Consider the following code segment:\nString message = \"Hello\";\nmessage = null;\nmessage = \"Goodbye\";\nSystem.out.println(message);\nWhat is printed?",
    choices: ["Hello", "null", "Goodbye", "The code fails to compile because message was set to null."],
    answer: 2, explanation: "A reference variable can be reassigned multiple times. The final assignment, \"Goodbye\", is what is printed." },
  { id: "1.4-c3", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "Which of the following assignment statements will NOT compile, given the declaration int count = 0;?",
    choices: ["count = 5;", "count = count + 1;", "count = 2.5;", "count = count * 2;"],
    answer: 2, explanation: "Assigning a double literal like 2.5 to an int variable without an explicit cast causes a compile-time error." },
  { id: "1.4-c4", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.B", prompt: "A program needs to read a line of text typed by the user at the keyboard. Which of the following best describes an appropriate approach in this course?",
    choices: ["Use the Math class to retrieve keyboard input.", "Use a Scanner object to obtain input from the keyboard.", "Input from the keyboard is outside the scope of Java entirely.", "Use the System.out class to read input."],
    answer: 1, explanation: "A Scanner object is used to obtain text input from the keyboard." },
  { id: "1.4-c5", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "What is printed as a result of executing the following code segment?\nint a = 2;\nint b = 5;\na = b;\nb = a + 3;\nSystem.out.println(a);\nSystem.out.println(b);",
    choices: ["2 then 5", "5 then 8", "5 then 5", "2 then 8"],
    answer: 1, explanation: "a is reassigned to b's value, 5. Then b is reassigned to a + 3 = 5 + 3 = 8." },
  // ===================== 1.1 ADDITIONAL =====================
  { id: "1.1-b8", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.A", prompt: "Which of the following is the best definition of an algorithm?",
    choices: ["A step-by-step process used to solve a problem or accomplish a task", "A programming language such as Java", "A type of syntax error", "A program that has already been compiled"],
    answer: 0, explanation: "An algorithm is a step-by-step process used to solve a problem or accomplish a task." },
  { id: "1.1-b9", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.A", prompt: "A treasure hunt clue gives directions like \"walk 10 steps north, turn left, walk 5 steps.\" This set of directions is best described as:",
    choices: ["Not an algorithm, since it isn't written in a programming language", "An algorithm, because it is a step-by-step sequence for accomplishing a task", "A compiler", "A syntax error"],
    answer: 1, explanation: "Algorithms can be written in plain language and still count as algorithms -- they don't need to be code." },
  { id: "1.1-b10", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.B", prompt: "Before a Java program can run, what must happen to its source code first?",
    choices: ["It must be compiled", "It must be printed", "It must be renamed", "It must be translated into English"],
    answer: 0, explanation: "Source code must be compiled before a Java program can run." },
  { id: "1.1-b11", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.B", prompt: "Which of the following is commonly used to write, compile, and run Java code all in one place?",
    choices: ["A spreadsheet", "An IDE (integrated development environment)", "A web browser", "A word processor"],
    answer: 1, explanation: "An IDE lets a programmer write, compile, and run code within a single tool." },
  { id: "1.1-b12", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.C", prompt: "Which type of error occurs while a program is running, rather than being caught before the program starts?",
    choices: ["Syntax error", "Run-time error", "A missing semicolon", "A compiler warning"],
    answer: 1, explanation: "Run-time errors occur during execution, unlike syntax errors, which are caught by the compiler beforehand." },
  { id: "1.1-b13", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.C", prompt: "A student writes \"pubic class Main\" instead of \"public class Main\" in their code. This mistake will most likely cause a:",
    choices: ["Syntax error", "Logic error", "Run-time error", "No error at all"],
    answer: 0, explanation: "Misspelling a keyword breaks the language's syntax rules, which the compiler catches as a syntax error." },
  { id: "1.1-b14", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.A", prompt: "If the steps of an algorithm are performed out of their intended order, what is most likely to happen?",
    choices: ["The algorithm may produce incorrect results", "The algorithm will always still work correctly", "The program will automatically fix the order", "The algorithm becomes a compiler"],
    answer: 0, explanation: "Sequencing matters -- performing steps out of order can produce incorrect results." },
  { id: "1.1-b15", course: "csa", topic: "1.1", tier: "basic", lo: "1.1.B", prompt: "What happens if a Java program contains an error that the compiler detects?",
    choices: ["The program cannot run until the error is fixed", "The program runs but skips the broken line", "The program runs more slowly", "The compiler fixes the error automatically"],
    answer: 0, explanation: "A compiler-detected (syntax) error must be fixed before the program can run at all." },

  { id: "1.1-i4", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "A student wants an algorithm to determine the smaller of two numbers, x and y. Which sequence of steps correctly accomplishes this for all values of x and y?",
    choices: ["Step 1: Compare x and y. Step 2: Store whichever value is smaller.", "Step 1: Always store x.", "Step 1: Add x and y. Step 2: Divide by 2.", "Step 1: Always store y."],
    answer: 0, explanation: "Comparing the two values and keeping the smaller one works correctly regardless of which value happens to be smaller." },
  { id: "1.1-i5", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "A student wants an algorithm to calculate the perimeter of a rectangle, given its length and width. Which of the following algorithms is correct?",
    choices: ["Step 1: Add the length and width. Step 2: Multiply the result by 2.", "Step 1: Multiply the length and width.", "Step 1: Add the length and width. Step 2: Divide the result by 2.", "Step 1: Multiply the length and width. Step 2: Multiply the result by 2."],
    answer: 0, explanation: "Perimeter of a rectangle is 2 times the sum of its length and width." },
  { id: "1.1-i6", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "A student wants an algorithm to determine whether a whole number is even. Which of the following approaches correctly determines this for any whole number?",
    choices: ["Step 1: Divide the number by 2. Step 2: If the remainder is 0, the number is even.", "Step 1: Check if the number is greater than 0.", "Step 1: Divide the number by 2. Step 2: If the result is a whole number greater than 1, the number is even.", "Step 1: Subtract 2 from the number repeatedly until reaching 0."],
    answer: 0, explanation: "A number is even exactly when dividing it by 2 leaves a remainder of 0." },
  { id: "1.1-i7", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "Which of the following correctly orders the steps for making a peanut butter sandwich, assuming the goal is spreading peanut butter between two slices of bread?",
    choices: ["Step 1: Get two slices of bread. Step 2: Spread peanut butter on one slice. Step 3: Place the other slice on top.", "Step 1: Place one slice on top of another. Step 2: Get two slices of bread. Step 3: Spread peanut butter.", "Step 1: Spread peanut butter on a plate. Step 2: Get bread. Step 3: Eat.", "Step 1: Get two slices of bread. Step 2: Place them together. Step 3: Spread peanut butter on the outside."],
    answer: 0, explanation: "Only this ordering places the steps in a sequence that actually accomplishes the goal." },
  { id: "1.1-i8", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.C", prompt: "A program that tracks inventory compiles and runs without crashing, but it consistently reports one fewer item than the actual count. What type of error is most likely present?",
    choices: ["Syntax error", "Logic error", "Run-time error", "Compiler error"],
    answer: 1, explanation: "The program runs fine but produces a consistently wrong result -- a logic error." },
  { id: "1.1-i9", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.C", prompt: "A program compiles successfully, but while running it unexpectedly terminates and displays a message about an invalid array index. What type of error is this?",
    choices: ["Syntax error", "Logic error", "Run-time error (exception)", "There is no error"],
    answer: 2, explanation: "The program crashes during execution due to an invalid operation -- this is a run-time error (exception)." },
  { id: "1.1-i10", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.B", prompt: "A student says, \"My program has a mistake, but it still lets me run it -- it just gives the wrong output.\" What does this tell you about the type of mistake?",
    choices: ["It cannot be a syntax error, since the compiler would have blocked the program from running", "It must be a syntax error", "It means the compiler is broken", "It means the program has no mistakes"],
    answer: 0, explanation: "Since the program was allowed to run, the compiler didn't detect a syntax error -- the mistake is elsewhere (most likely a logic error)." },
  { id: "1.1-i11", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "A server wants an algorithm to calculate a tip amount based on a bill total and a tip percentage (as a decimal, like 0.20 for 20%). Which algorithm is correct?",
    choices: ["Step 1: Multiply the bill total by the tip percentage.", "Step 1: Add the bill total and the tip percentage.", "Step 1: Divide the bill total by the tip percentage.", "Step 1: Subtract the tip percentage from the bill total."],
    answer: 0, explanation: "The tip amount is the bill total multiplied by the tip rate." },
  { id: "1.1-i12", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "A student wants an algorithm to determine the largest of two numbers, m and n, then double it. Which sequence of steps is correct?",
    choices: ["Step 1: Compare m and n, keep the larger. Step 2: Multiply the result by 2.", "Step 1: Multiply m by 2. Step 2: Compare the result to n.", "Step 1: Add m and n. Step 2: Divide by 2.", "Step 1: Multiply m and n. Step 2: Keep the larger original value."],
    answer: 0, explanation: "Finding the larger value first, then doubling that result, correctly accomplishes the task." },
  { id: "1.1-i13", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.C", prompt: "Which of the following is generally true about when syntax errors versus logic errors are discovered?",
    choices: ["Syntax errors are caught by the compiler before the program runs; logic errors are typically found by testing the program while it runs", "Both are always caught by the compiler before the program runs", "Logic errors are caught by the compiler; syntax errors are found through testing", "Neither type of error can be found before the program is submitted"],
    answer: 0, explanation: "Syntax errors block compilation, while logic errors require running and testing the program to notice incorrect output." },
  { id: "1.1-i14", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.A", prompt: "A cashier wants an algorithm to calculate the total cost of a purchase including tax, given a subtotal and a tax rate (as a decimal). Which sequence of steps is correct?",
    choices: ["Step 1: Multiply the subtotal by the tax rate to get the tax amount. Step 2: Add the tax amount to the subtotal.", "Step 1: Add the subtotal and tax rate. Step 2: Multiply by 2.", "Step 1: Divide the subtotal by the tax rate.", "Step 1: Subtract the tax rate from the subtotal."],
    answer: 0, explanation: "The total is the subtotal plus the tax amount, and the tax amount is the subtotal times the tax rate." },
  { id: "1.1-i15", course: "csa", topic: "1.1", tier: "intermediate", lo: "1.1.B", prompt: "Many IDEs underline certain code in red before the program is even run. What is this feature most likely doing?",
    choices: ["Performing real-time syntax checking, similar to what the compiler will check", "Running the program in the background", "Randomly highlighting code", "Fixing logic errors automatically"],
    answer: 0, explanation: "Many IDEs continuously check for syntax problems as you type, before you ever compile or run the program." },

  { id: "1.1-c7", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.A", prompt: "A student designs an algorithm to calculate a weighted average of two test scores, where the first score counts twice as much as the second. Which algorithm is correct?",
    choices: ["Step 1: Multiply the first score by 2. Step 2: Add the second score. Step 3: Divide the result by 3.", "Step 1: Add the two scores. Step 2: Divide by 2.", "Step 1: Multiply the first score by 2. Step 2: Add the second score. Step 3: Divide the result by 2.", "Step 1: Add the two scores. Step 2: Divide by 3."],
    answer: 0, explanation: "Weighting the first score twice means the total \"weight\" is 3 (2 + 1), so the sum must be divided by 3, not 2." },
  { id: "1.1-c8", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.B", prompt: "A student calls a method with the wrong number of arguments, and the code fails to compile. Separately, a different program compiles fine but crashes when a method is called on an object that was never created. Which best describes these two situations?",
    choices: ["Both are syntax errors, caught at compile time.", "The first is a syntax error caught at compile time; the second is a run-time error (exception) that occurs during execution.", "The first is a run-time error; the second is a syntax error.", "Both are logic errors found only through testing."],
    answer: 1, explanation: "A mismatched method call is caught by the compiler (syntax error). Calling a method on an object that doesn't exist causes a run-time exception, since it can only be detected once the program actually executes that line." },
  { id: "1.1-c9", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.C", prompt: "Situation 1: A program uses a variable that was never declared, so it will not compile. Situation 2: A program compiles and runs, but a formula is missing a step and computes the wrong result every time. Situation 3: A program compiles and runs correctly for most inputs, but crashes with a \"NullPointerException\" for one specific input. Which of the following correctly identifies each situation's error type?",
    choices: ["1: Syntax error, 2: Logic error, 3: Run-time error (exception)", "1: Logic error, 2: Syntax error, 3: Run-time error", "1: Run-time error, 2: Logic error, 3: Syntax error", "1: Syntax error, 2: Run-time error, 3: Logic error"],
    answer: 0, explanation: "1 is caught by the compiler (syntax). 2 always produces a wrong result due to a flawed formula (logic). 3 only fails for specific input during execution (run-time exception)." },
  { id: "1.1-c10", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.A", prompt: "A store applies a discount only if a purchase total is over $50, then adds tax to whatever the final total is. A student writes an algorithm that adds tax first and then checks for the discount. For which purchase totals would this produce a different (incorrect) result compared to the intended order?",
    choices: ["For purchases where the discount would apply, since tax would be calculated on the pre-discount amount", "For no purchases -- the order never matters here", "For all purchases, regardless of total", "Only for purchases under $50"],
    answer: 0, explanation: "If tax is calculated before the discount is applied, any purchase that should have received a discount will end up with tax computed on the wrong (higher) amount, changing the final total." },
  { id: "1.1-c11", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.C", prompt: "A program processes a list of scores and works correctly for lists of 5 or more scores, but crashes with an \"ArrayIndexOutOfBoundsException\" whenever the list has fewer than 5 scores. Which best describes this situation?",
    choices: ["A syntax error, since it only happens sometimes", "A run-time error (exception) that only manifests for certain inputs, since the compiler cannot detect input-dependent problems", "A logic error, since the compiler should have caught it", "Not a real error, since it works most of the time"],
    answer: 1, explanation: "This is a run-time exception -- the compiler can't predict what input values the program will receive, so a problem that only appears with specific inputs can only be discovered by running the program with those inputs." },
  { id: "1.1-c12", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.B", prompt: "Segment 1 has a string literal that is missing its closing quotation mark. Segment 2 has correct syntax throughout, but calls a method using a variable that was never assigned a value before that point. Which best describes what happens with each?",
    choices: ["Both fail to compile.", "Segment 1 fails to compile (syntax error); Segment 2 also fails to compile, since Java requires local variables to be definitely assigned before use.", "Segment 1 compiles and runs; Segment 2 fails to compile.", "Both compile and run without any errors."],
    answer: 1, explanation: "An unterminated string literal is a syntax error. Using a local variable before it has been assigned a value is also caught at compile time in Java, not left as a run-time surprise." },
  { id: "1.1-c13", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.A", prompt: "A student designs an algorithm to determine whether three given side lengths can form a triangle (the sum of any two sides must be greater than the third). Which sequence of checks correctly determines this for all cases?",
    choices: ["Check that (a + b > c) AND (a + c > b) AND (b + c > a)", "Check only that a + b > c", "Check that a, b, and c are all positive numbers", "Check that a equals b equals c"],
    answer: 0, explanation: "All three combinations must be checked, since failing any one of them means the sides cannot form a triangle." },
  { id: "1.1-c14", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.C", prompt: "A program appears to work correctly during normal testing, but a teacher suspects it might fail for unusual inputs like 0 or negative numbers. For which type of error would testing with these edge-case values be most useful in finding a problem?",
    choices: ["Syntax errors, which edge cases have no effect on", "Logic errors or run-time errors that only appear for specific input values", "Only errors that occur during compilation", "This kind of testing cannot reveal any type of error"],
    answer: 1, explanation: "Edge-case testing is specifically useful for surfacing logic errors or run-time errors that don't show up with typical, \"normal\" input values." },
  { id: "1.1-c15", course: "csa", topic: "1.1", tier: "complex", lo: "1.1.A", prompt: "A programmer correctly designs an algorithm in plain English to calculate a shipping cost, but makes a typo while translating it into Java, causing a compiler error. Which of the following is true?",
    choices: ["The algorithm itself is still correct; the mistake is in the implementation, not the underlying logic", "The algorithm is incorrect, since it does not compile", "An algorithm and its Java implementation are always the same thing", "The compiler error means the plain-English steps must be rewritten from scratch"],
    answer: 0, explanation: "An algorithm's correctness is independent of any particular implementation. A typo introduced while translating it into code is an implementation-level syntax error, not a flaw in the algorithm's logic." },

  // ===================== 1.2 ADDITIONAL =====================
  { id: "1.2-b7", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "Which of the following correctly declares and initializes a boolean variable named isRaining to false?",
    choices: ["boolean isRaining = false;", "boolean isRaining = \"false\";", "bool isRaining = false;", "isRaining boolean = false;"],
    answer: 0, explanation: "boolean isRaining = false; correctly declares and initializes a boolean variable." },
  { id: "1.2-b8", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "A programmer needs to store the price of an item, which may include cents (such as 19.99). Which data type is most appropriate?",
    choices: ["int", "double", "boolean", "String"],
    answer: 1, explanation: "double is the primitive type used for decimal values like prices." },
  { id: "1.2-b9", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.A", prompt: "Which of the following is a primitive type in this course?",
    choices: ["int", "String", "Robot", "Object"],
    answer: 0, explanation: "int is one of the three primitive types (int, double, boolean) used in this course; the others are reference types." },
  { id: "1.2-b10", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.A", prompt: "A String variable is best described as a:",
    choices: ["Primitive type", "Reference type", "Boolean type", "Numeric type"],
    answer: 1, explanation: "String is a reference type, since it is not one of the three primitive types used in this course." },
  { id: "1.2-b11", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "Which of the following correctly declares an int variable representing the number of pets someone owns, initialized to 2?",
    choices: ["int numPets = 2;", "int numPets = 2.0;", "numPets int = 2;", "int numPets = \"2\";"],
    answer: 0, explanation: "int numPets = 2; correctly declares and initializes an int variable with a whole-number literal." },
  { id: "1.2-b12", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "Given the declaration boolean hasSiblings;, which of the following could be legally assigned to it?",
    choices: ["true", "\"yes\"", "1", "0"],
    answer: 0, explanation: "A boolean variable can only hold true or false, not strings or numbers." },
  { id: "1.2-b13", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.B", prompt: "Which of the following values could NOT be directly assigned to an int variable without a cast?",
    choices: ["3.5", "3", "-7", "0"],
    answer: 0, explanation: "3.5 is a double literal; assigning it to an int variable requires an explicit cast." },
  { id: "1.2-b14", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.A", prompt: "A class named Song is used to create objects representing songs. A variable declared as Song favoriteSong; is a:",
    choices: ["Reference type", "Primitive type", "Boolean value", "Compiler keyword"],
    answer: 0, explanation: "Song is not one of the three primitive types, so favoriteSong is a reference type variable." },
  { id: "1.2-b15", course: "csa", topic: "1.2", tier: "basic", lo: "1.2.A", prompt: "Which of the following is NOT one of the three primitive data types used in this course?",
    choices: ["char", "int", "double", "boolean"],
    answer: 0, explanation: "Only int, double, and boolean are the primitive types covered in this course; char is outside its scope." },

  { id: "1.2-i4", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A weather app needs variables to represent the current temperature (which may include decimals) and whether it is currently sunny. Which pair of declarations is most appropriate?",
    choices: ["double temperature; boolean isSunny;", "int temperature; int isSunny;", "boolean temperature; double isSunny;", "double temperature; double isSunny;"],
    answer: 0, explanation: "A decimal temperature fits double; a true/false condition fits boolean." },
  { id: "1.2-i5", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A fitness app needs variables to represent the number of steps taken (a whole number) and whether a daily goal was met. Which pair of declarations is most appropriate?",
    choices: ["int steps; boolean goalMet;", "double steps; int goalMet;", "boolean steps; boolean goalMet;", "int steps; double goalMet;"],
    answer: 0, explanation: "A whole-number step count fits int; a true/false condition fits boolean." },
  { id: "1.2-i6", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.B", prompt: "A student declares a variable using the statement: double distance = 10; Which of the following is true?",
    choices: ["This is invalid because 10 is not written with a decimal point.", "This is valid; the int value 10 is automatically widened to the double value 10.0.", "This is valid, but distance will store the value as an int.", "This will cause a run-time error."],
    answer: 1, explanation: "An int literal can be assigned to a double variable and is automatically widened -- here, to 10.0." },
  { id: "1.2-i7", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A class named Book is used to create objects representing books. Which of the following statements about a variable declared as Book currentBook; is true?",
    choices: ["currentBook is a reference type variable, since Book is not one of the three primitive types.", "currentBook is a primitive type variable.", "currentBook can only store true or false.", "currentBook must be declared using the keyword double."],
    answer: 0, explanation: "Since Book isn't int, double, or boolean, a Book variable is a reference type." },
  { id: "1.2-i8", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A library system needs variables to represent the number of pages in a book (a whole number) and whether the book is currently checked out. Which pair of declarations is most appropriate?",
    choices: ["int pageCount; boolean isCheckedOut;", "boolean pageCount; int isCheckedOut;", "double pageCount; double isCheckedOut;", "int pageCount; int isCheckedOut;"],
    answer: 0, explanation: "A whole-number page count fits int; a true/false status fits boolean." },
  { id: "1.2-i9", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.B", prompt: "Which of the following correctly declares and initializes a double variable named average with the value 88, without using a decimal point in the literal?",
    choices: ["double average = 88;", "double average = \"88\";", "int average = 88.0;", "double average = 88f;"],
    answer: 0, explanation: "The int literal 88 is automatically widened to a double value when assigned to a double variable." },
  { id: "1.2-i10", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A music player app needs a variable to represent the length of a song, which may include a fractional number of seconds, and a variable to represent whether the song is currently playing. Which pair of declarations is most appropriate?",
    choices: ["double songLength; boolean isPlaying;", "int songLength; int isPlaying;", "boolean songLength; double isPlaying;", "double songLength; double isPlaying;"],
    answer: 0, explanation: "A fractional length fits double; a true/false playing status fits boolean." },
  { id: "1.2-i11", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.B", prompt: "A student wants to declare a variable to store the number of students in a class, which will always be a whole number. Which is the most appropriate declaration?",
    choices: ["int numStudents;", "double numStudents;", "boolean numStudents;", "String numStudents;"],
    answer: 0, explanation: "A count that is always a whole number is best represented with int." },
  { id: "1.2-i12", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A vending machine program needs a variable to represent whether an item is in stock and a variable for its price, which may include cents. Which pair of declarations is most appropriate?",
    choices: ["boolean inStock; double price;", "int inStock; int price;", "double inStock; boolean price;", "boolean inStock; int price;"],
    answer: 0, explanation: "A true/false status fits boolean; a price with cents fits double." },
  { id: "1.2-i13", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.B", prompt: "Which of the following declarations would cause a compile-time error?",
    choices: ["int age = 15.5;", "double age = 15;", "int age = 15;", "double age = 15.5;"],
    answer: 0, explanation: "Assigning a double literal like 15.5 to an int variable without a cast is a compile-time error." },
  { id: "1.2-i14", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.A", prompt: "A garden-tracking app needs a variable for a plant's height (which may include decimals) and a variable for whether it needs watering today. Which pair of declarations is most appropriate?",
    choices: ["double height; boolean needsWater;", "int height; int needsWater;", "boolean height; double needsWater;", "double height; int needsWater;"],
    answer: 0, explanation: "A decimal height fits double; a true/false condition fits boolean." },
  { id: "1.2-i15", course: "csa", topic: "1.2", tier: "intermediate", lo: "1.2.B", prompt: "A student writes: boolean isFull = 1; Why does this cause a compile-time error?",
    choices: ["Because a boolean variable can only be assigned true or false, not a number", "Because 1 is not a valid Java literal", "Because isFull is not a valid variable name", "It does not cause an error"],
    answer: 0, explanation: "Unlike some other languages, Java booleans cannot be assigned numeric values like 1 or 0." },

  { id: "1.2-c6", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.A", prompt: "Consider the following declarations: double balance; boolean isOverdrawn; String accountHolder; int transactionCount; Which of these variables is a reference type?",
    choices: ["accountHolder", "balance", "isOverdrawn", "transactionCount"],
    answer: 0, explanation: "String is not one of the three primitive types, so accountHolder is the reference type here." },
  { id: "1.2-c7", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.B", prompt: "A quiz app needs to track the number of questions answered correctly (a whole number) and the percentage score (which may include decimals, like 87.5). Which pair of declarations is most appropriate?",
    choices: ["int numCorrect; double percentage;", "double numCorrect; int percentage;", "boolean numCorrect; boolean percentage;", "int numCorrect; int percentage;"],
    answer: 0, explanation: "A whole-number count fits int; a decimal percentage fits double." },
  { id: "1.2-c8", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.B", prompt: "A student attempts to declare a variable as: long distance = 1000000; Which of the following best explains why this is problematic in the context of this course?",
    choices: ["long is not one of the three primitive data types (int, double, boolean) covered in this course; int or double should be used instead.", "1000000 is too large to be a valid literal.", "distance is not a legal variable name.", "Java does not support variables that store distances."],
    answer: 0, explanation: "Only int, double, and boolean are used in this course; long, though a real Java type, is outside its scope." },
  { id: "1.2-c9", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.A", prompt: "A delivery app needs to track: the estimated delivery time in minutes (a whole number), whether the package has left the warehouse, and the total distance in miles (which may include decimals). Which set of declarations is most appropriate?",
    choices: ["int minutes; boolean hasLeft; double distance;", "double minutes; int hasLeft; boolean distance;", "boolean minutes; double hasLeft; int distance;", "int minutes; int hasLeft; int distance;"],
    answer: 0, explanation: "A whole-number time fits int, a true/false status fits boolean, and a decimal distance fits double." },
  { id: "1.2-c10", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.B", prompt: "Which of the following code segments will NOT compile?",
    choices: ["boolean done = \"true\";", "int count = 0;", "double rate = 0;", "boolean done = true;"],
    answer: 0, explanation: "\"true\" is a String literal (in quotes), not the boolean value true, so this cannot be assigned to a boolean variable." },
  { id: "1.2-c11", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.A", prompt: "A class named Ticket is used to create objects representing event tickets. A program also has an int variable seatNumber and a boolean variable isValid. Which of the following statements is true?",
    choices: ["A variable of type Ticket is a reference type, while seatNumber and isValid are primitive types.", "All three variables are reference types.", "All three variables are primitive types.", "seatNumber is a reference type, but a Ticket variable is primitive."],
    answer: 0, explanation: "Ticket is a class (not one of the three primitive types), making it a reference type, while int and boolean are primitive types." },
  { id: "1.2-c12", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.B", prompt: "A student needs a variable to represent a bank account balance that could be negative (overdrawn) and may include cents. Which of the following is most appropriate, and why?",
    choices: ["double balance; -- because balances can include decimal cents and negative values, both of which double supports", "int balance; -- because balances are always whole numbers", "boolean balance; -- because an account is either overdrawn or not", "double balance; declared as unsigned, since balances can't be negative"],
    answer: 0, explanation: "double supports both decimal values and negative numbers, both of which a balance may need." },
  { id: "1.2-c13", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.A", prompt: "Consider the declarations: int score; String playerName; boolean isWinner; double timeElapsed; A student claims that exactly two of these are reference types. Is this claim correct?",
    choices: ["No -- only one of these (playerName) is a reference type; the rest are primitive.", "Yes -- playerName and isWinner are both reference types.", "Yes -- score and timeElapsed are both reference types.", "No -- none of these are reference types."],
    answer: 0, explanation: "Only String is not one of the three primitive types here, so only playerName is a reference type." },
  { id: "1.2-c14", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.B", prompt: "A student writes the following two declarations in the same program: int total = 10; double total = 10.5; What is the result?",
    choices: ["A compile-time error, since total is declared twice in the same scope", "Both declarations succeed, and total ends up storing 10.5", "Both declarations succeed, and total ends up storing 10", "A run-time error occurs when the program executes"],
    answer: 0, explanation: "Declaring two variables with the same name in the same scope is a compile-time error in Java." },
  { id: "1.2-c15", course: "csa", topic: "1.2", tier: "complex", lo: "1.2.A", prompt: "A parking app needs to track whether a spot is compact-car-only (true/false), the hourly rate (which may include cents), and a Vehicle object currently parked there. Which best matches each piece of data to an appropriate type category?",
    choices: ["isCompactOnly: boolean (primitive); hourlyRate: double (primitive); parkedVehicle: Vehicle (reference)", "isCompactOnly: Vehicle (reference); hourlyRate: boolean (primitive); parkedVehicle: double (primitive)", "All three should be declared as primitive types", "All three should be declared as reference types"],
    answer: 0, explanation: "A true/false condition and a decimal rate are both primitive types (boolean and double), while a Vehicle object is a reference type." },

  // ===================== 1.3 ADDITIONAL =====================
  { id: "1.3-b8", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.A", prompt: "Which method call moves the cursor to a new line after printing its output?",
    choices: ["System.out.println()", "System.out.print()", "System.in.read()", "System.out.write()"],
    answer: 0, explanation: "println moves the cursor to a new line after printing; print does not." },
  { id: "1.3-b9", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.B", prompt: "Which of the following is a valid string literal in Java?",
    choices: ["\"Hello, world!\"", "Hello, world!", "'Hello, world!'", "(Hello, world!)"],
    answer: 0, explanation: "A string literal must be enclosed in double quotation marks." },
  { id: "1.3-b10", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.B", prompt: "What does the escape sequence \\t represent inside a string?",
    choices: ["A tab character", "A new line", "A backslash", "A double quote"],
    answer: 0, explanation: "\\t inserts a tab character." },
  { id: "1.3-b11", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.C", prompt: "What is the result of the expression 15 / 4, where both values are int literals?",
    choices: ["3.75", "3", "4", "3.0"],
    answer: 1, explanation: "Integer division truncates the decimal portion, so 15 / 4 evaluates to 3." },
  { id: "1.3-b12", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.C", prompt: "What is the result of the expression 15.0 / 4?",
    choices: ["3", "3.75", "4", "3.0"],
    answer: 1, explanation: "Since one operand is a double, the full decimal quotient 3.75 is computed." },
  { id: "1.3-b13", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.C", prompt: "What is the value of the expression 20 % 6?",
    choices: ["3", "2", "0", "3.33"],
    answer: 1, explanation: "20 divided by 6 is 3 with a remainder of 2." },
  { id: "1.3-b14", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.A", prompt: "What is printed as a result of System.out.println(\"Hi\"); followed by System.out.println(\"Bye\");?",
    choices: ["HiBye", "Hi Bye", "Hi\nBye", "Bye\nHi"],
    answer: 2, explanation: "Each println call prints its text and then moves to a new line, so \"Hi\" and \"Bye\" appear on separate lines." },
  { id: "1.3-b15", course: "csa", topic: "1.3", tier: "basic", lo: "1.3.C", prompt: "In Java, which operator computes the remainder of a division?",
    choices: ["%", "/", "*", "//"],
    answer: 0, explanation: "The % (modulo) operator computes the remainder of integer division." },

  { id: "1.3-i4", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of y after the following code executes?\nint y = 4 + 2 * 5;",
    choices: ["30", "14", "22", "9"],
    answer: 1, explanation: "Multiplication happens before addition: 2 * 5 = 10, then 4 + 10 = 14." },
  { id: "1.3-i5", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of result after the following code executes?\ndouble result = 7 / 2 + 1.5;",
    choices: ["5.0", "5.5", "4.5", "6.0"],
    answer: 2, explanation: "7 / 2 is int division, giving 3. Then 3 + 1.5 = 4.5, which is stored as the double value 4.5." },
  { id: "1.3-i6", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.B", prompt: "What is printed as a result of the following statement?\nSystem.out.println(\"Line1\\nLine2\");",
    choices: ["Line1Line2", "Line1\\nLine2 (printed literally)", "Line1 followed by Line2 on the next line", "An error occurs"],
    answer: 2, explanation: "The \\n escape sequence causes a line break between Line1 and Line2." },
  { id: "1.3-i7", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of z after the following code executes?\nint z = 3 * 4 - 6 / 2;",
    choices: ["3", "9", "0", "6"],
    answer: 1, explanation: "Multiplication and division happen first, left to right: 3*4=12, 6/2=3, then 12 - 3 = 9." },
  { id: "1.3-i8", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.A", prompt: "What is printed as a result of executing:\nSystem.out.print(\"Total: \");\nSystem.out.print(25);\nSystem.out.println();\nSystem.out.print(\"Done\");",
    choices: ["Total: 25\nDone", "Total: 25Done", "Total: \n25Done", "Total:25\nDone"],
    answer: 0, explanation: "The two print calls share a line (\"Total: 25\"), then println() (with no arguments) moves to a new line before \"Done\" is printed." },
  { id: "1.3-i9", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of the expression 8 % 3 + 8 / 3?",
    choices: ["4", "2.67", "5", "2"],
    answer: 0, explanation: "8 % 3 = 2, and 8 / 3 = 2 (int division). 2 + 2 = 4." },
  { id: "1.3-i10", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.B", prompt: "Which of the following correctly prints a backslash character?",
    choices: ["System.out.print(\"\\\\\");", "System.out.print(\"\\\");", "System.out.print(\"/\");", "System.out.print(\"\\b\");"],
    answer: 0, explanation: "\\\\ is the escape sequence for printing a single literal backslash character." },
  { id: "1.3-i11", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of avg after the following code executes?\ndouble avg = (3 + 4 + 5) / 3;",
    choices: ["4.0", "4", "3.33", "4.33"],
    answer: 0, explanation: "3+4+5 = 12, and 12 / 3 is int division giving 4, which is then widened to the double value 4.0 when stored." },
  { id: "1.3-i12", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of n after the following code executes?\nint n = 2 * (3 + 4);",
    choices: ["14", "10", "9", "24"],
    answer: 0, explanation: "Parentheses are evaluated first: 3 + 4 = 7, then 2 * 7 = 14." },
  { id: "1.3-i13", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.A", prompt: "A student wants to print a value followed immediately by more text on the same line. Which method should be used for the first print call?",
    choices: ["print, not println", "println, not print", "Either works identically", "Neither can be used for this"],
    answer: 0, explanation: "print does not move to a new line, so the next output continues on the same line." },
  { id: "1.3-i14", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.C", prompt: "What is the value of the expression 6 / 4 * 2?",
    choices: ["2", "3.0", "0", "1"],
    answer: 0, explanation: "Operators of equal precedence evaluate left to right: 6 / 4 (int division) = 1, then 1 * 2 = 2." },
  { id: "1.3-i15", course: "csa", topic: "1.3", tier: "intermediate", lo: "1.3.B", prompt: "What is printed as a result of the statement:\nSystem.out.println(\"Tab:\\tEnd\");",
    choices: ["Tab:End", "Tab: followed by a tab character, then End", "An error occurs", "Tab:\\tEnd printed literally"],
    answer: 1, explanation: "\\t inserts an actual tab character between \"Tab:\" and \"End\"." },

  { id: "1.3-c7", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "What is the value of x after the following code executes?\nint x = 10 / 3 * 3;",
    choices: ["10", "9", "3", "1"],
    answer: 1, explanation: "10 / 3 (int division) = 3, then 3 * 3 = 9 -- note this does NOT equal 10, because the remainder was already discarded by the first division." },
  { id: "1.3-c8", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "What happens when the following code executes?\nint a = 8;\nint b = 4 - 4;\nSystem.out.println(a % b);",
    choices: ["Prints 0", "Prints 8", "Throws an ArithmeticException", "Fails to compile"],
    answer: 2, explanation: "b evaluates to 0, and computing a remainder with a divisor of 0 throws an ArithmeticException, just like division by zero does." },
  { id: "1.3-c9", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "What is the value of result after the following code executes?\ndouble result = 5 / 2 + 5 / 2.0;",
    choices: ["5.0", "4.5", "5.5", "2.5"],
    answer: 1, explanation: "5 / 2 (int division) = 2. 5 / 2.0 = 2.5. Then 2 + 2.5 = 4.5." },
  { id: "1.3-c10", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.A", prompt: "What is printed as a result of the following code segment?\nfor (int i = 0; i < 3; i++) {\n  System.out.print(i);\n}\nSystem.out.println(\"done\");",
    choices: ["012done", "0 1 2 done", "012\ndone", "0\n1\n2\ndone"],
    answer: 0, explanation: "print keeps everything on the same line, so the loop prints 0, 1, 2 with no separators, then \"done\" appends right after on that same line." },
  { id: "1.3-c11", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "What is the value of x after the following code executes?\nint x = 5;\nx = x % 2 + x / 2;",
    choices: ["3", "2", "1", "5"],
    answer: 0, explanation: "5 % 2 = 1, and 5 / 2 = 2 (int division, using the original value of x before it's reassigned). 1 + 2 = 3." },
  { id: "1.3-c12", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "A student wants an expression that always rounds a positive double value x down to the nearest whole number and stores it as an int. Which of the following correctly accomplishes this?",
    choices: ["(int) x", "(int) (x + 0.5)", "x % 1", "(double) x"],
    answer: 0, explanation: "Casting a double to an int truncates (drops) the decimal portion, which rounds down for positive values." },
  { id: "1.3-c13", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "What is the value of total after the following code executes?\nint total = 100 % 30 % 4;",
    choices: ["2", "0", "10", "1"],
    answer: 0, explanation: "Operators of equal precedence evaluate left to right: 100 % 30 = 10, then 10 % 4 = 2." },
  { id: "1.3-c14", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.B", prompt: "What is printed as a result of the following statement?\nSystem.out.println(\"Price: $\" + 5 + 3);",
    choices: ["Price: $53", "Price: $8", "Price: $5 3", "An error occurs"],
    answer: 0, explanation: "Once a String is involved, + performs concatenation left to right: \"Price: $\" + 5 becomes \"Price: $5\", then + 3 appends the text \"3\", giving \"Price: $53\" rather than adding the numbers." },
  { id: "1.3-c15", course: "csa", topic: "1.3", tier: "complex", lo: "1.3.C", prompt: "Which of the following expressions evaluates to a different result than the other three?",
    choices: ["7 / 2", "(double) 7 / 2", "7 / 2.0", "7.0 / 2"],
    answer: 0, explanation: "7 / 2 uses int division and evaluates to 3, while the other three all involve a double somewhere and evaluate to 3.5." },

  // ===================== 1.4 ADDITIONAL =====================
  { id: "1.4-b7", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "In the statement total = total + 5;, what does the right-hand side represent?",
    choices: ["An expression that is evaluated before being assigned to total", "A separate variable named 'total + 5'", "A syntax error", "A comment"],
    answer: 0, explanation: "The right-hand side is an expression; it's evaluated first, and the resulting value is then stored in total." },
  { id: "1.4-b8", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "Which of the following is true about assignment statements in Java?",
    choices: ["The right-hand side is evaluated first, then its value is stored in the variable on the left", "The left-hand side is evaluated first", "Both sides are evaluated at the same time with no order", "Assignment statements do not evaluate expressions"],
    answer: 0, explanation: "Java evaluates the right-hand expression first, then assigns the resulting value to the left-hand variable." },
  { id: "1.4-b9", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "Which of the following can be assigned the value null?",
    choices: ["A String variable", "An int variable", "A double variable", "A boolean variable"],
    answer: 0, explanation: "null can only be assigned to reference type variables, such as String; it cannot be assigned to primitive types." },
  { id: "1.4-b10", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.B", prompt: "What is the primary purpose of a Scanner object in this course?",
    choices: ["To read input typed by the user", "To perform mathematical calculations", "To print text to the screen", "To compile the program"],
    answer: 0, explanation: "A Scanner object is used to read input, such as text typed by the user." },
  { id: "1.4-b11", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "What is the value of b after the following code executes?\nint a = 7;\nint b = a;",
    choices: ["7", "0", "a", "An error occurs"],
    answer: 0, explanation: "b is assigned the current value of a, which is 7." },
  { id: "1.4-b12", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "Which of the following correctly reassigns the variable count to the value 10?",
    choices: ["count = 10;", "int count = 10;", "10 = count;", "count == 10;"],
    answer: 0, explanation: "count = 10; reassigns the existing variable count. (Declaring it again with int would be a compile error if it already exists; == is comparison, not assignment.)" },
  { id: "1.4-b13", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "A variable that has been declared but not yet assigned a value is described as:",
    choices: ["Uninitialized", "Null", "Zero", "A syntax error"],
    answer: 0, explanation: "A declared variable with no value assigned yet is called uninitialized." },
  { id: "1.4-b14", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.A", prompt: "What is printed as a result of the following code?\nint x = 3;\nx = 8;\nSystem.out.println(x);",
    choices: ["8", "3", "11", "An error occurs"],
    answer: 0, explanation: "The second assignment overwrites the first; x holds 8 by the time it is printed." },
  { id: "1.4-b15", course: "csa", topic: "1.4", tier: "basic", lo: "1.4.B", prompt: "Before using a Scanner object to read from the keyboard, what must a program typically do first?",
    choices: ["Create (instantiate) a Scanner object", "Compile the Scanner class", "Delete any existing variables", "Print a blank line"],
    answer: 0, explanation: "A Scanner object must be created before it can be used to read input." },

  { id: "1.4-i4", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "What is printed as a result of executing the following code segment?\nint x = 10;\nx = x - 4;\nx = x * 3;\nSystem.out.print(x);",
    choices: ["18", "30", "6", "26"],
    answer: 0, explanation: "x becomes 10 - 4 = 6, then 6 * 3 = 18." },
  { id: "1.4-i5", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "Consider the following code segment:\nString status = null;\nstatus = \"Active\";\nSystem.out.println(status);\nWhat is printed?",
    choices: ["Active", "null", "An error occurs, since status was null", "Nothing is printed"],
    answer: 0, explanation: "A reference variable can be reassigned after being null; the final value, \"Active\", is what gets printed." },
  { id: "1.4-i6", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "Consider the following code segment:\nint m = 6;\nint n = 9;\nint temp = m;\nm = n;\nn = temp;\nSystem.out.println(m);\nSystem.out.println(n);\nWhat is printed?",
    choices: ["9 then 6", "6 then 9", "6 then 6", "9 then 9"],
    answer: 0, explanation: "This sequence swaps the values: m becomes 9 (n's original value), and n becomes 6 (saved in temp)." },
  { id: "1.4-i7", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "What is printed as a result of executing the following code?\nint score = 50;\nscore = score + 25;\nscore = score - 10;\nSystem.out.print(score);",
    choices: ["65", "75", "40", "85"],
    answer: 0, explanation: "score becomes 50 + 25 = 75, then 75 - 10 = 65." },
  { id: "1.4-i8", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "Consider the following code segment:\nString a = \"cat\";\nString b = a;\na = \"dog\";\nSystem.out.println(b);\nWhat is printed?",
    choices: ["cat", "dog", "null", "An error occurs"],
    answer: 0, explanation: "b was assigned the value of a (\"cat\") before a was changed to \"dog\", so b still holds \"cat\"." },
  { id: "1.4-i9", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.B", prompt: "A program needs to ask the user to type their age and then use that value in a calculation. Which of the following best describes the appropriate approach?",
    choices: ["Use a Scanner object to read the typed value, then store it in a variable", "Directly assign the value the user is thinking of to a variable", "Use System.out to read the value", "This cannot be done in Java"],
    answer: 0, explanation: "A Scanner object reads the value the user types, which can then be stored in a variable for use in the program." },
  { id: "1.4-i10", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "What is printed as a result of the following code segment?\nint a = 1;\nint b = 2;\nint c = 3;\na = b;\nb = c;\nc = a;\nSystem.out.println(a + \" \" + b + \" \" + c);",
    choices: ["2 3 2", "1 2 3", "3 2 1", "2 3 3"],
    answer: 0, explanation: "a becomes 2 (b's value). b becomes 3 (c's value). c becomes 2 (a's NEW value, since a was already reassigned)." },
  { id: "1.4-i11", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "Consider the following code segment:\ndouble price = 20;\nprice = price - 5;\nprice = price * 2;\nSystem.out.println(price);\nWhat is printed?",
    choices: ["30.0", "15.0", "40.0", "10.0"],
    answer: 0, explanation: "price becomes 20 - 5 = 15, then 15 * 2 = 30, stored and printed as the double value 30.0." },
  { id: "1.4-i12", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "A student writes: int x; x = x + 1; Which best describes what happens?",
    choices: ["A compile-time error, since x is used before being assigned a value", "x becomes 1", "x becomes 0", "A run-time exception occurs"],
    answer: 0, explanation: "x must be assigned a value before it can appear on the right-hand side of an expression; this fails to compile." },
  { id: "1.4-i13", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "What is printed as a result of the following code?\nboolean flag = true;\nflag = false;\nSystem.out.println(flag);",
    choices: ["false", "true", "0", "An error occurs"],
    answer: 0, explanation: "flag is reassigned to false before being printed." },
  { id: "1.4-i14", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.B", prompt: "Why might a program display a prompt message, like \"Enter your name:\", right before reading input with a Scanner?",
    choices: ["To let the user know what kind of input the program expects them to type", "Because Scanner requires a prompt to function", "To fix a syntax error", "Prompts are required by the compiler"],
    answer: 0, explanation: "A prompt is simply good practice to tell the user what input is expected -- it isn't required by Scanner itself." },
  { id: "1.4-i15", course: "csa", topic: "1.4", tier: "intermediate", lo: "1.4.A", prompt: "What is printed as a result of the following code segment?\nint x = 5;\nint y = x + 2;\nx = 100;\nSystem.out.println(y);",
    choices: ["7", "100", "102", "5"],
    answer: 0, explanation: "y was computed as x + 2 = 7 at the time of assignment; changing x afterward does not change y's already-stored value." },

  { id: "1.4-c6", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "What is printed as a result of the following code segment?\nint a = 4;\nint b = 7;\na = a + b;\nb = a - b;\na = a - b;\nSystem.out.println(a + \" \" + b);",
    choices: ["7 4", "4 7", "11 4", "4 11"],
    answer: 0, explanation: "This is a classic arithmetic swap: a becomes 11, then b becomes 11-7=4, then a becomes 11-4=7. Final values: a=7, b=4." },
  { id: "1.4-c7", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "Consider the following code segment:\nString x = \"A\";\nString y = \"B\";\nString temp = x;\nx = y;\ny = temp;\nx = x + y;\nSystem.out.println(x);\nSystem.out.println(y);\nWhat is printed?",
    choices: ["BA then A", "AB then B", "A then B", "B then A"],
    answer: 0, explanation: "The swap makes x = \"B\" and y = \"A\". Then x = x + y becomes \"B\" + \"A\" = \"BA\". Final: x prints \"BA\", y prints \"A\"." },
  { id: "1.4-c8", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "A student writes the following, intending to swap the values of two int variables a and b, without using a third variable:\na = a + b;\nb = a - b;\na = a - b;\nFor which of the following starting values would this technique fail to work as intended?",
    choices: ["It works correctly for all int values of a and b, as long as a + b does not overflow past Integer.MAX_VALUE", "It only works when a and b are equal", "It never works correctly", "It only works when a is greater than b"],
    answer: 0, explanation: "This arithmetic swap technique is mathematically valid for any values, with the one caveat that the intermediate sum a + b must not overflow beyond the int range." },
  { id: "1.4-c9", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "Consider the following code segment:\nint count = 0;\ncount = count + 1;\ncount = count + count;\ncount = count * count;\nSystem.out.println(count);\nWhat is printed?",
    choices: ["4", "2", "6", "9"],
    answer: 0, explanation: "count: 0 -> 1 (add 1) -> 2 (add itself: 1+1) -> 4 (multiply itself: 2*2)." },
  { id: "1.4-c10", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "A method contains the following code, where numerator and denominator are int parameters:\nint result;\nif (denominator != 0) {\n  result = numerator / denominator;\n}\nSystem.out.println(result);\nWhat is the issue with this code?",
    choices: ["It fails to compile, since result might not be assigned a value if the condition is false", "It always prints 0", "It throws an ArithmeticException", "There is no issue; this code is correct"],
    answer: 0, explanation: "Java requires local variables to be definitely assigned before use along every possible path -- since result might never be assigned if the if-condition is false, this fails to compile." },
  { id: "1.4-c11", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.B", prompt: "A student wants to read two separate values typed by a user: their age (a whole number) and their name (text). Which best describes an appropriate approach using Scanner?",
    choices: ["Use one Scanner object, calling the appropriate method for each type of input needed", "Create a brand new Scanner object for every single value read", "This requires two different classes, since Scanner can only read one type of input ever", "Scanner cannot read more than one value in the same program"],
    answer: 0, explanation: "A single Scanner object can be reused to read multiple values of different types over the course of a program." },
  { id: "1.4-c12", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "What is printed as a result of the following code segment?\nString a = \"x\";\nString b = \"y\";\nString c = a;\na = b;\nb = c;\nc = a + b;\nSystem.out.println(a + b + c);",
    choices: ["yxyx", "xyxy", "xyyx", "yxxy"],
    answer: 0, explanation: "After the swap: a=\"y\", b=\"x\". Then c = a+b = \"yx\". Final concatenation a+b+c = \"y\"+\"x\"+\"yx\" = \"yxyx\"." },
  { id: "1.4-c13", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "Consider the following code segment:\nint x = 5;\nint y = x;\ny = y + 10;\nx = x + y;\nSystem.out.println(x);\nSystem.out.println(y);\nWhat is printed?",
    choices: ["20 then 15", "15 then 20", "5 then 15", "20 then 5"],
    answer: 0, explanation: "y starts as 5 (copy of x), becomes 15 after +10. Then x becomes 5 + 15 = 20. Final: x=20, y=15." },
  { id: "1.4-c14", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "A programmer wants a method's local variable to definitely have a value assigned to it in every possible execution path, no matter which branch of an if/else statement runs. Which of the following approaches guarantees this?",
    choices: ["Assign the variable a default value before the if/else, or assign it within every branch of the if/else", "Assign it only in the if branch", "Assign it only in the else branch", "It is impossible to guarantee this in Java"],
    answer: 0, explanation: "Java requires a local variable to be definitely assigned along every path before use; giving it a value in every branch (or a default value beforehand) satisfies that requirement." },
  { id: "1.4-c15", course: "csa", topic: "1.4", tier: "complex", lo: "1.4.A", prompt: "What is printed as a result of the following code segment?\nint a = 2;\nint b = 3;\nint c = 4;\na = b;\nb = c;\nc = a + b + c;\nSystem.out.println(a + \" \" + b + \" \" + c);",
    choices: ["3 4 11", "2 3 4", "3 4 9", "4 3 2"],
    answer: 0, explanation: "a becomes 3 (b's original value). b becomes 4 (c's original value). c becomes a+b+c using the NEW a and b plus the ORIGINAL c (4): 3+4+4=11." },
];
